name: gaussianpro
channels:
  - anaconda
  - main
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - tqdm
  - ninja
  - matplotlib=3.5.3
  - pip:
      - opencv-python==4.10.0.84
      - open3d==0.17.0
      - imageio==2.31.2
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
